language: perl6
sudo: false
os:
  - linux
perl6:
  - latest
install:
  - rakudobrew build zef
  - git clone https://github.com/p6-pdf/PDF-Class-p6.git
  - zef install PDF-Class-p6
  - zef --depsonly install .
script:
  - prove -ve "perl6 -I."
  - zef install .
